import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

import { cn } from "@/lib/utils";
import Header from "@/components/header";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Receipt Reader",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("font-sans antialiased", fontSans.variable)}>
				<Header />
				<div className="px-4 pt-4">{children}</div>
				<Toaster richColors />
			</body>
		</html>
	);
}
